### ISSUE TITLE
Pipeline mentioned in section `3.10` stopped working

### ISSUE THREAD

**Issue by mribeirodantas** [seqeralabs/nf-training-public#118]
The following pipeline stopped working:
```
nextflow run rnaseq-nf -with-docker -with-report -with-trace -with-timeline -with-dag dag.png
```
It works if one specifies the `dev` revision with `-r dev`, but this is a very old one and shouldn't be used. By investigating the errors, it seems to be the way modules are called in the `include` instruction.

**Comment by chriswyatt1** [comment]
Which container version are you running?. Ah, maybe the old container does not work because the code has changed in rnaseq-nf. The new container works fine (https://github.com/seqeralabs/nf-training-public/pull/114), so we should switch asap.

<img width="886" alt="image" src="https://user-images.githubusercontent.com/9978862/194018980-71692759-fd03-464b-8c00-447cacbcdd37.png">

**Comment by abhi18av** [comment]
@chriswyatt1 , maybe we should make use of the tags here to maintain reproducibility?

The workaround of using `-r dev` worked, but the `dev` branch is really quite behind (~2 years).

**Comment by chriswyatt1** [comment]
@abhi18av how do you mean? As in we should publish the current branch of the training with the older container as V1, and make the new container version V2?

**Comment by abhi18av** [comment]
Exactly!

Since we rely heavily on the rnaseq-nf pipeline during the training it's better to make use of the tags so that we don't run across surprises within the training material and the latest master can continue moving forward to accommodate new developments in NF runtime.

**Comment by mribeirodantas** [comment]
It's working now.
